// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMlpNau9ol2PW_ZhkqLxAC-54hMno_axY',
    appId: '1:352591970314:web:a9a76e0d98ed27e2f95ff3',
    messagingSenderId: '352591970314',
    projectId: 'fbase-auth-riverpod',
    authDomain: 'fbase-auth-riverpod.firebaseapp.com',
    storageBucket: 'fbase-auth-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLdN6a4FSp9svKxImr9FgwmKkeaUfoN8',
    appId: '1:352591970314:android:c8ff26a01bca9022f95ff3',
    messagingSenderId: '352591970314',
    projectId: 'fbase-auth-riverpod',
    storageBucket: 'fbase-auth-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11TLQdmw01Tsby2l1VNOhRkOGb10JjeA',
    appId: '1:352591970314:ios:33e23d1eabfd86faf95ff3',
    messagingSenderId: '352591970314',
    projectId: 'fbase-auth-riverpod',
    storageBucket: 'fbase-auth-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11TLQdmw01Tsby2l1VNOhRkOGb10JjeA',
    appId: '1:352591970314:ios:33e23d1eabfd86faf95ff3',
    messagingSenderId: '352591970314',
    projectId: 'fbase-auth-riverpod',
    storageBucket: 'fbase-auth-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMlpNau9ol2PW_ZhkqLxAC-54hMno_axY',
    appId: '1:352591970314:web:e122486f9c49bbfef95ff3',
    messagingSenderId: '352591970314',
    projectId: 'fbase-auth-riverpod',
    authDomain: 'fbase-auth-riverpod.firebaseapp.com',
    storageBucket: 'fbase-auth-riverpod.firebasestorage.app',
  );

}